version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - ./src/database/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'